# Generated by Django 5.2 on 2025-05-07 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cómo_nos_conoció',
            field=models.CharField(blank=True, choices=[('amigo', 'Por un amigo'), ('redes', 'Redes sociales'), ('busqueda', 'Búsqueda en internet'), ('otros', 'Otros')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dirección',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='municipio',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='logica.municipio'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='provincia',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='logica.provincia'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='teléfono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='logica.zona'),
        ),
    ]
