# Generated by Django 5.2 on 2025-05-07 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0002_alter_usuario_cómo_nos_conoció_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='logica.municipio'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='logica.provincia'),
        ),
    ]
